# Generated by Django 3.0.4 on 2020-03-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_basico', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='escolas',
            new_name='escola',
        ),
    ]
